version: '3.1'

services:
  redis:
    image: redis:7.4.2 
    container_name: redis # better to name it as "matching-redis" since it's used by matching service
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
  db:
    image: mysql:latest
    container_name: user-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    ports:
      - 3308:3306

volumes:
  redis-data:
