version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: user-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    ports:
      - 3308:3306