version: '3.1'

services:
  app:
    build: .
    container_name: qa-game-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      - QAGAME_DB_PARAMS_USERNAME=root
      - QAGAME_DB_PARAMS_PASSWORD=12345
    networks:
      - qa-game-network

  redis:
    image: redis:7.4.2 
    container_name: matching-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    networks:
      - qa-game-network

  db:
    image: mysql:latest
    container_name: user-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    ports:
      - 3308:3306
    networks:
      - qa-game-network

networks:
  qa-game-network:
    driver: bridge

volumes:
  redis-data: