type: yml

db_params:
# better to not include here
  host: "127.0.0.1"
  port: 3308
  db_name: "users"

  max_life_time: "3m"
  max_open_conn: 10
  max_idle_conn: 10

redis_params:
  host: "localhost"
  port: 6379
  password: "" # TODO: implement later using env variables
  db: 0

scheduler:
  match_players_cronjob_intervals_in_mins: "0/5"

auth_params:
  access_token_duration:  "24h"
  refresh_token_duration: "7d"

server_params:
  host: "localhost"
  port: 8080

matching_service_params:
  max_num_of_users_to_be_fetched_in_each_iter: 100
  waiting_timeout: "30m"
  waiting_prefix: "waiting-list"

presence_svc:
  expected_online_time: "5m" 
  prefix: "presence"