type: yml

app_params:
  pprof_host: "localhost"
  pprof_port: 8090

db_params:
# TODO: better to not include here
  host: "db"
  port: 3306
  db_name: "users"

  max_life_time: "3m"
  max_open_conn: 10
  max_idle_conn: 10

redis_params:
  host: "redis"
  port: 6379
  password: "" # TODO: implement later using env variables
  db: 0

scheduler:
  match_players_cronjob_intervals_in_mins: "*"

auth_params:
  access_token_duration:  "24h"
  refresh_token_duration: "7d"

server_params:
  host: "0.0.0.0"
  port: 8080

matching_service_params:
  max_num_of_users_to_be_fetched_in_each_iter: 100
  waiting_timeout: "1h"
  waiting_prefix: "waiting-list"

presence_svc:
  expected_online_time: "30m" 
  prefix: "presence"