// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.1
// source: contract/presence/presence.proto

package presence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsersAvailabilityInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint64               `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersAvailabilityInfoRequest) Reset() {
	*x = GetUsersAvailabilityInfoRequest{}
	mi := &file_contract_presence_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersAvailabilityInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersAvailabilityInfoRequest) ProtoMessage() {}

func (x *GetUsersAvailabilityInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_presence_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersAvailabilityInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUsersAvailabilityInfoRequest) Descriptor() ([]byte, []int) {
	return file_contract_presence_presence_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersAvailabilityInfoRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersAvailabilityInfoResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UsersInfo     []*UserAvailabilityInfo `protobuf:"bytes,1,rep,name=users_info,json=usersInfo,proto3" json:"users_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersAvailabilityInfoResponse) Reset() {
	*x = GetUsersAvailabilityInfoResponse{}
	mi := &file_contract_presence_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersAvailabilityInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersAvailabilityInfoResponse) ProtoMessage() {}

func (x *GetUsersAvailabilityInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_presence_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersAvailabilityInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUsersAvailabilityInfoResponse) Descriptor() ([]byte, []int) {
	return file_contract_presence_presence_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersAvailabilityInfoResponse) GetUsersInfo() []*UserAvailabilityInfo {
	if x != nil {
		return x.UsersInfo
	}
	return nil
}

type UserAvailabilityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastOnlineAt  int64                  `protobuf:"varint,2,opt,name=last_online_at,json=lastOnlineAt,proto3" json:"last_online_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAvailabilityInfo) Reset() {
	*x = UserAvailabilityInfo{}
	mi := &file_contract_presence_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAvailabilityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAvailabilityInfo) ProtoMessage() {}

func (x *UserAvailabilityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_contract_presence_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAvailabilityInfo.ProtoReflect.Descriptor instead.
func (*UserAvailabilityInfo) Descriptor() ([]byte, []int) {
	return file_contract_presence_presence_proto_rawDescGZIP(), []int{2}
}

func (x *UserAvailabilityInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserAvailabilityInfo) GetLastOnlineAt() int64 {
	if x != nil {
		return x.LastOnlineAt
	}
	return 0
}

var File_contract_presence_presence_proto protoreflect.FileDescriptor

var file_contract_presence_presence_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73,
	0x22, 0x58, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x55, 0x0a, 0x14, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x41,
	0x74, 0x32, 0x72, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x20, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contract_presence_presence_proto_rawDescOnce sync.Once
	file_contract_presence_presence_proto_rawDescData = file_contract_presence_presence_proto_rawDesc
)

func file_contract_presence_presence_proto_rawDescGZIP() []byte {
	file_contract_presence_presence_proto_rawDescOnce.Do(func() {
		file_contract_presence_presence_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_presence_presence_proto_rawDescData)
	})
	return file_contract_presence_presence_proto_rawDescData
}

var file_contract_presence_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contract_presence_presence_proto_goTypes = []any{
	(*GetUsersAvailabilityInfoRequest)(nil),  // 0: GetUsersAvailabilityInfoRequest
	(*GetUsersAvailabilityInfoResponse)(nil), // 1: GetUsersAvailabilityInfoResponse
	(*UserAvailabilityInfo)(nil),             // 2: UserAvailabilityInfo
}
var file_contract_presence_presence_proto_depIdxs = []int32{
	2, // 0: GetUsersAvailabilityInfoResponse.users_info:type_name -> UserAvailabilityInfo
	0, // 1: PresenceService.GetUsersAvailabilityInfo:input_type -> GetUsersAvailabilityInfoRequest
	1, // 2: PresenceService.GetUsersAvailabilityInfo:output_type -> GetUsersAvailabilityInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contract_presence_presence_proto_init() }
func file_contract_presence_presence_proto_init() {
	if File_contract_presence_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_presence_presence_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_presence_presence_proto_goTypes,
		DependencyIndexes: file_contract_presence_presence_proto_depIdxs,
		MessageInfos:      file_contract_presence_presence_proto_msgTypes,
	}.Build()
	File_contract_presence_presence_proto = out.File
	file_contract_presence_presence_proto_rawDesc = nil
	file_contract_presence_presence_proto_goTypes = nil
	file_contract_presence_presence_proto_depIdxs = nil
}
